name: Build

on:
  push:
    branches:
      - 'master'
      - '*.x'
      - '!1.*'
      - '!2.*'
      - '!3.0.*'
      - '!3.1.*'
  pull_request:
      branches:
        - 'master'
        - '*.x'
        - '!1.*'
        - '!2.*'
        - '!3.0.*'
        - '!3.1.*'
      types:
        - opened
        - reopened
        - synchronize
        - labeled

jobs:
  build:
    name: Build package ğŸ“¦
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'build-wheel')
    steps:
      - uses: actions/checkout@v4
        with:
          # prefer head commit over merge commit in case of PRs
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      - uses: actions/setup-python@v5
        name: Set up Python ğŸ
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements.dev.txt
      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          node-version: 18.x
      - name: Install build deps ğŸ”§
        run: |
          sudo apt-get install libpq-dev
          pip install --user -U pip setuptools wheel
          pip install --user -e '.[dev]'
      - name: Install npm deps â˜•
        run: npm ci
      - name: Build wheel ğŸ—
        run: ./bin/maintenance/build-wheel.py indico --add-version-suffix
      - uses: actions/upload-artifact@v3
        name: Upload build artifacts ğŸ“¦
        with:
          name: indico-wheel
          retention-days: 7
          path: ./dist
